/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }]

  // But you can create a sidebar manually
  tutorialSidebar: [
    'welcome',
    'getting-started/intro',
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/why-quantaleap/intro',
        'introduction/how-it-works/intro',
        {
          type: 'category',
          label: 'Use cases',
          link: {
            type: 'generated-index',
            title: 'Use cases',
            description:
              'This is our hub to start learning and building workflows!',
            slug: '/use-cases'
          },
          items: [
            'use-cases/vm-cpu',
            'use-cases/vm-shut-down',
            'use-cases/cost-alert',
            'use-cases/tagging-policy'
          ]
        }
      ]
    }
  ]
}

module.exports = sidebars
